// app-vue/src/App.vue
<template>
  <div id="app">
    <AppHeader/>
    <LedControl/>
    <RosData />
    <RealTimeChart  />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AppHeader from "./components/AppHeader.vue"
import RosData from "./components/RosData.vue";
import RealTimeChart from './components/RealTimeChart.vue';
import LedControl from './components/LedControl.vue';

export default defineComponent({
  name: "App",
  components: {
    AppHeader,
    RosData,
    LedControl,
    RealTimeChart,
  },

});
</script>

// app-react/src/App.tsx
import React from "react";
import Header from "./components/Header";
import RosData from "./components/RosData";
import RealTimeChart from "./components/RealTimeChart";
import LedControl from "./components/LedControl";

const App: React.FC = () => {
  return (
    <div>
      <Header />
      <LedControl />
      <RosData />
      <RealTimeChart />
    </div>
  );
};

export default App;
