// app-vue/src/components/RosData.vue
<template>
    <div>
      <p>Message: {{ message }}</p>
    </div>
  </template>
  
  <script lang="ts">
  import { defineComponent, ref, onMounted, onUnmounted } from 'vue';
  
  export default defineComponent({
    name: 'RosData',
    setup() {
      const message = ref("");
      let eventSource: EventSource;
  
      onMounted(() => {
        eventSource = new EventSource(process.env.VUE_APP_API_HOST_URL + '/api/sensor'); // replace with your Next.js API URL
  
        eventSource.onmessage = (event) => {
          const data = JSON.parse(event.data);
          message.value = data;
        };
      });
  
      onUnmounted(() => {
        eventSource.close();
      });
  
      return { message };
    }
  });
  </script>

// app-react/src/components/RosData.tsx
import React, { useEffect, useState } from "react";

const RosData: React.FC = () => {
  const [message, setMessage] = useState<string>("");

  useEffect(() => {
    const eventSource = new EventSource(
      process.env.REACT_APP_API_HOST_URL + "/api/sensor"
    );

    eventSource.onmessage = (event) => {
      const data = JSON.parse(event.data);
      setMessage(data);
    };

    return () => {
      eventSource.close();
    };
  }, []);

  return (
    <div>
      <p>Message: {JSON.stringify(message)}</p>
    </div>
  );
};

export default RosData;
