// app-react/src/components/LedControl.tsx
import React, { useState } from "react";
import axios from "axios";
// import { config } from "dotenv";

// config();
const LedControl: React.FC = () => {
  const [ledState, setLedState] = useState<"on" | "off">("off");

  const updateLedState = async (newState: "on" | "off") => {
    setLedState(newState);
    try {
      const response = await axios.post(
        process.env.REACT_APP_HOST_URL + "/api/led",
        {
          state: newState,
        }
      );
      console.log(response.data);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div>
      LED Control:
      <input
        type="radio"
        id="on"
        value="on"
        checked={ledState === "on"}
        onChange={() => updateLedState("on")}
      />
      <label htmlFor="on">On</label>
      <input
        type="radio"
        id="off"
        value="off"
        checked={ledState === "off"}
        onChange={() => updateLedState("off")}
      />
      <label htmlFor="off">Off</label>
    </div>
  );
};

export default LedControl;

// app-vue/src/components/LedControl.vue
<template>
  <div>
    LED Control:
    <input type="radio" id="on" value="on" v-model="ledState" @change="updateLedState">
    <label for="on">On</label>
    <input type="radio" id="off" value="off" v-model="ledState" @change="updateLedState">
    <label for="off">Off</label>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      ledState: 'off',
    }
  },
  methods: {
    async updateLedState() {
      try {
        const response = await axios.post(process.env.VUE_APP_HOST_URL + '/api/led', { state: this.ledState });
        console.log(response.data);
      } catch (error) {
        console.error(error);
      }
    }
  }
}
</script>
