// app-react/src/components/RealTimeChart.tsx
import React, { useEffect, useState } from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts";

interface ChartData {
  time: string;
  value: number;
}

const RealTimeChart: React.FC = () => {
  const [data, setData] = useState<ChartData[]>([]);

  useEffect(() => {
    const eventSource = new EventSource(
      process.env.REACT_APP_API_HOST_URL + "/api/sensor"
    );

    eventSource.onmessage = (event) => {
      const receivedData = JSON.parse(event.data);

      setData((prevData) => {
        const newData = [
          ...prevData,
          { time: new Date().toLocaleTimeString(), value: receivedData.data },
        ];

        // If the length of newData is greater than 100, only keep the last 50 elements
        if (newData.length > 100) {
          return newData.slice(-100);
        }

        // Otherwise, return the whole array
        return newData;
      });
    };

    return () => {
      eventSource.close();
    };
  }, []);

  return (
    <LineChart width={500} height={300} data={data}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="time" />
      <YAxis />
      <Tooltip />
      <Line type="monotone" dataKey="value" stroke="#8884d8" />
    </LineChart>
  );
};

export default RealTimeChart;

// app-vue/src/components/RealTimeChart.vue
<template>
  <div style="height:300px; width:600px">
    <LineChart :data="chartData" :options="chartOptions"></LineChart>
    <!-- <LineChart :chart-data="chartData" :chart-options="chartOptions" ></LineChart> -->

  </div>
</template>

<script>
/* eslint-disable */
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { Line as LineChart } from 'vue-chartjs'
// import LineChart from './LineChart.vue'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
} from 'chart.js'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
)

export default {
  components: {
    LineChart
  },
  setup() {
    const chartData = ref({
      labels: [],
      datasets: [
        {
          label: 'Data',
          backgroundColor: '#f87979',
          data: []
        }
      ]
    });

    let eventSource; // Declare the eventSource variable

    onMounted(() => {
      eventSource = new EventSource(process.env.VUE_APP_API_HOST_URL+'/api/sensor');

      eventSource.onmessage = event => {
        const receivedData = JSON.parse(event.data);

        // chartData.value.labels.push(new Date().toLocaleTimeString());
        // chartData.value.datasets[0].data.push(receivedData.data);

        // if (chartData.value.labels.length > 50) {
        //   chartData.value.labels.shift();
        //   chartData.value.datasets[0].data.shift();
        // }

          chartData.value = {
            labels: [...chartData.value.labels, new Date().toLocaleTimeString()].slice(-50),
            datasets: [
              {
                ...chartData.value.datasets[0],
                data: [...chartData.value.datasets[0].data, receivedData.data].slice(-50)
              }
            ]
          }

        // console.log("chartData", chartData)
      };
    });

    onUnmounted(() => {
      if (eventSource) {
        eventSource.close();
      }
    });

    return {
      chartData,
      chartOptions: {
        // Add your chart options here
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          y: {
            min: 0,
            max: 0.3
          }
        },
        layout: {
          padding: {
            top: 10,
            right: 10,
            bottom: 10,
            left: 10,
          },
        },
      }
    };
  }
};
</script>
